### get root
GET localhost:3001


### get all boats
GET localhost:3001/api/boats/
Accept: application/json

### add one boat
POST localhost:3001/api/boats
Content-Type: application/json
Accept: application/json

{
"boat_name": "faster harder",
"boat_type": "quad"
}

> {%
 client.test("request executed", () => {
 client.assert(response.status === 204, "Response is not 204.")
 })
 %}

### Get boats by name
GET localhost:3001/api/boats/name/longer


### Delete one boat by object id
DELETE localhost:3001//api/boats/{{_id_}}

> {%
  client.test("request executed", () => {
client.assert(response.status === 204, "Response for delete is not 204")
})
%}

### get a specific boat
GET localhost:3001/api/boats/{{_id_}}
Accept: application/json


